doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_mapping: true
        # naming_strategy removed — using explicit ORM Table annotations
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        metadata_cache_driver:
            type: pool
            pool: doctrine.cache
        query_cache_driver:
            type: pool
            pool: doctrine.cache
        result_cache_driver:
            type: pool
            pool: doctrine.cache
