scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        issuer: KanjiReview
        server_name: '%env(DEFAULT_URI)%'
        template: security/two_factor_verify.html.twig
